Repository DreamTeam2k25/Aurora_Backend, pull requests merged in 2025-01, with the labels that each got.

#6 FEAT: Initialize django project [Refs: #1]
  .gitignore
  config/__init__.py
  config/asgi.py
  config/settings.py
  config/urls.py
  config/wsgi.py
  core/aurora/__init__.py
  core/aurora/admin.py
  core/aurora/apps.py
  core/aurora/migrations/__init__.py
  core/aurora/models/__init__.py
  core/aurora/serializers/__init__.py
  core/aurora/tests.py
  core/aurora/views/__init__.py
  core/authentication/__init__.py
  core/authentication/admin.py
  core/authentication/apps.py
  core/authentication/migrations/__init__.py
  core/authentication/models/__init__.py
  core/authentication/serializers/__init__.py
  core/authentication/tests.py
  core/authentication/views/__init__.py
  manage.py
  pdm.lock
  pyproject.toml
  src/aurora_backend/__init__.py
  tests/__init__.py
Labels: enhancement

#7 FEAT: Create the models in auth app [Refs: #2]
  config/settings.py
  config/urls.py
  core/authentication/admin.py
  core/authentication/migrations/0001_initial.py
  core/authentication/migrations/0002_alter_user_password.py
  core/authentication/migrations/0003_office_guildmember_student.py
  core/authentication/models/__init__.py
  core/authentication/models/guild_member.py
  core/authentication/models/student.py
  core/authentication/models/user.py
  core/authentication/serializers/__init__.py
  core/authentication/serializers/user.py
  core/authentication/views/__init__.py
  core/authentication/views/user.py
  pdm.lock
  pyproject.toml
Labels: enhancement

#8 Feat 3
  .gitignore
  .vscode/settings.json
  LICENSE
  config/__init__.py
  config/asgi.py
  config/settings.py
  config/urls.py
  config/wsgi.py
  core/aurora/__init__.py
  core/aurora/admin.py
  core/aurora/apps.py
  core/aurora/migrations/__init__.py
  core/aurora/models/__init__.py
  core/aurora/serializers/__init__.py
  core/aurora/tests.py
  core/aurora/views/__init__.py
  core/authentication/__init__.py
  core/authentication/admin.py
  core/authentication/apps.py
  core/authentication/migrations/0001_initial.py
  core/authentication/migrations/0002_alter_user_password.py
  core/authentication/migrations/0003_office_guildmember_student.py
  core/authentication/migrations/0004_rename_guildmember_guildmemberdata_and_more.py
  core/authentication/migrations/0005_alter_guildmemberdata_office_and_more.py
  core/authentication/migrations/0006_alter_student_is_guild_member.py
  core/authentication/migrations/__init__.py
  core/authentication/models/__init__.py
  core/authentication/models/guild_member.py
  core/authentication/models/student.py
  core/authentication/models/user.py
  core/authentication/serializers/__init__.py
  core/authentication/serializers/guild_member.py
  core/authentication/serializers/student.py
  core/authentication/serializers/user.py
  core/authentication/tests.py
  core/authentication/utils/__init__.py
  core/authentication/utils/alter_guild_member.py
  core/authentication/utils/turma_select.py
  core/authentication/views/__init__.py
  core/authentication/views/student.py
  core/authentication/views/user.py
  manage.py
  pdm.lock
  pyproject.toml
  src/aurora_backend/__init__.py
  tests/__init__.py
Labels: bug, enhancement, good first issue

#9 Feat 3
  .vscode/settings.json
  LICENSE
  config/settings.py
  config/urls.py
  core/authentication/admin.py
  core/authentication/migrations/0004_rename_guildmember_guildmemberdata_and_more.py
  core/authentication/migrations/0005_alter_guildmemberdata_office_and_more.py
  core/authentication/migrations/0006_alter_student_is_guild_member.py
  core/authentication/models/__init__.py
  core/authentication/models/guild_member.py
  core/authentication/models/student.py
  core/authentication/models/user.py
  core/authentication/serializers/__init__.py
  core/authentication/serializers/guild_member.py
  core/authentication/serializers/student.py
  core/authentication/serializers/user.py
  core/authentication/utils/__init__.py
  core/authentication/utils/alter_guild_member.py
  core/authentication/utils/turma_select.py
  core/authentication/views/__init__.py
  core/authentication/views/student.py
  core/authentication/views/user.py
  pdm.lock
  pyproject.toml
Labels: enhancement, good first issue

#11 Refactor: Improve validation and error handling in authentication ser…
  config/settings.py
  core/authentication/serializers/student.py
  core/authentication/serializers/user.py
  core/authentication/utils/alter_guild_member.py
  core/authentication/utils/turma_select.py
  core/authentication/views/student.py
Labels: enhancement, refact
